### ISSUE TITLE
Reolink Subfolders

### ISSUE THREAD

**Issue by schabau** [lukelalo/gallery-card#12]
Hello,

I have a Reolink camera that sends recordings to HA via FTP.
The folder structure used by Reolink is very impractical and cannot be changed. Either you don't use any subfolders at all, or a subfolder is created for the year and month, and if desired, also for the day.

So, options like this would have to be set, but that doesn't work.

```
entities:
  - media-source://media_source/local/reolink
folder_format: YYYY/MM/DD
search_date_folder_format: YYYY/MM/DD
```

Is this configurable in any way?

Best regards,
Detlef Paschke

**Comment by dyptan-io** [comment]
This is how I did it for my Reolink recordings, but you would need to turn off the subfolders camera settings:

```yaml
- type: custom:gallery-card
  entities:
   - media-source://media_source/recording/
  menu_alignment: Bottom
  show_duration: false
  file_name_date_begins: 14
  file_name_format: YYYYMMDDHHmmss
  caption_format: " "
```


<img width="508" height="281" alt="Image" src="https://github.com/user-attachments/assets/eafc20dc-933e-45a4-b5e1-9c29191cadd1" />
