### ISSUE TITLE
How to make card work with Nest camera event clips

### ISSUE THREAD

**Issue by dnestico** [lukelalo/gallery-card#8]
Hi I have a Nest doorbell camera and all the event video clips the doorbell creates are saved in to home assistant automatically under its own "Nest" folder, I am trying to get that displayed on this card but it's not working, not sure what I'm doing wrong and how I can make it work, thanks.

Card code I'm using
```
type: custom:gallery-card
menu_alignment: Bottom
maximum_files: 20
entities:
  - path: media-source://media_source/nest/
    recursive: true
```

Video attached to make it easy to understand:

https://github.com/user-attachments/assets/f4e8c1f5-27fb-4202-9bf9-825e39adc4dd
